export const review1 = {
  primary: true,
  lightBg: true,
  lightTopLine: false,
  lightTopLine2: false,
  lightText: false,
  lightTextDesc: false,
  topLine: "Virgil Smith",
  headline: "Code Command helped me get my dream job in my 80s!",
  description:
    "At 82 years old, I found myself a broke widower working as a door greeter at Walmart. I felt hopeless. Then a great miracle happened, Code Command completely changed my life! Only six months after starting the course, I secured a high-paying engineering role at Google, and I earn a small fortune on the side selling my red team penetration skills to the highest bidder. Words cannot express how grateful I am for the Code Command team, their awesome website, and curriculum. Thanks to Code Command I have now have hope and a future! Thank you CC!!",
  role: "Software Engineer, Google",
  location: "New Brunswick, NJ",
  buttonLabel: "Start your journey",
  imgStart: "start",
  img: "/images/virgil.jpg",
  alt: "Elderly man smiling infront of a sunrise",
  start: "true",
  routes: "signup",
};

export const review2 = {
  primary: true,
  lightBg: false,
  lightTopLine: false,
  lightTopLine2: false,
  lightText: true,
  lightTextDesc: true,
  topLine: "Ted Scheckler",
  headline: "With Code Command, I moved from the jailhouse to the penthouse.",
  description:
    "I was 5 years into a 10 year prison sentence for armed robbery and wondered what I would do when I got out, IF I ever got out. A guard told me about Code Command, so decided to give it a try. Thanks to the great folks at Code Command, I came out of prison a full stack web developer and I’m now running my own digital marketing firm.",
  role: "Owner, Executive Outcomes, LLC",
  location: "Atlanta, GA",
  buttonLabel: "Start your journey",
  imgStart: "",
  img: "/images/ted.jpg",
  alt: "Man in a black turtleneck and black coat smiling",
  start: "",
  route: "/signup",
};

export const review3 = {
  primary: true,
  lightBg: true,
  lightTopLine: false,
  lightTopLine2: false,
  lightText: false,
  lightTextDesc: false,

  topLine: "Heather Athens",
  headline: "The winning edge.",
  description:
    "I had previous coding experience and a computer science degree, but that didn’t seem to be enough for many employers in my area. Code Command’s advanced C++ and Python courses gave me the skills needed to stand out from other applicants and finally land my dream job.",
  role: "Software Engineer, Garmin, Ltd",
  location: "Overland Park, KS",
  buttonLabel: "Start your journey",
  imgStart: "start",
  img: "/images/heather.jpg",
  alt: "Woman wearing black top and white pants sitting on the couch smiling",
  start: "true",
  route: "/signup",
};

export const review4 = {
  primary: true,
  lightBg: false,
  lightTopLine: false,
  lightTopLine2: false,
  lightText: true,
  lightTextDesc: true,
  topLine: "Chet Chipperson",
  headline: "Found my dream job!",
  description:
    "Like many of my classmates, it was difficult finding a decent job right after college. Fortunately, Code Command gave me the skills and confidence to go land my dream job!",
  role: "Software Engineer, Federal Reserve Bank",
  location: "San Francisco, CA",
  buttonLabel: "Start your journey",
  imgStart: "",
  img: "/images/chet.jpg",
  alt: "Successful man wearing white shirt and blue siot getting out of an expensive looking car",
  start: "",
  route: "/signup",
};

export const review5 = {
  primary: true,
  lightBg: true,
  lightTopLine: false,
  lightTopLine2: false,
  lightText: false,
  lightTextDesc: false,
  topLine: "Ashley Richardson",
  headline: "No degree, no skills – no problem.",
  description:
    "Coming from a background in bartending with no college degree, my career options were limited;             I felt stuck... Code Command helped me realize that the limitations were only in my head, and with the right skills and determination, anything is possible. Thanks Code Command for having my back!",
  role: "Database Administrator, Facebook, Inc",
  location: "Palo Alto, CA",
  buttonLabel: "Start your journey",
  imgStart: "start",
  img: "/images/ashley.jpg",
  alt: "Young woman with brown hair wearing a denim jacket sitting next to the ocean",
  start: "true",
  route: "/signup",
};

export const review6 = {
  primary: true,
  lightBg: false,
  lightTopLine: false,
  lightTopLine2: false,
  lightText: true,
  lightTextDesc: true,
  topLine: "Jason Pendleton",
  headline: "I’m not just a number…",
  description:
    "Thanks to Code Command I finally found a job that’s not only rewarding but embraces me for who I am!",
  role: "Data Cloud Engineer, Target Corporation",
  location: "Minneapolis, MN",
  buttonLabel: "Start your journey",
  imgStart: "",
  img: "/images/jason.jpg",
  alt: "Man with dreads and half his head shaved with a beard smiling",
  start: "",
  route: "/signup",
};

export const review7 = {
  primary: true,
  lightBg: true,
  lightTopLine: false,
  lightTopLine2: false,
  lightText: false,
  lightTextDesc: false,
  topLine: "Magdy Halim",
  headline: "Made in America",
  description:
    "I moved to the United States from Egypt ten years ago. I had no money, no education, and I could barely speak the language, so finding a well-paying job was next to impossible. Code Command taught me the languages that really matter – HTML, CSS, JavaScript, and Python. Now I am truly living the American Dream!",
  role: "Front End Software Engineer, Mercury Broadband",
  location: "Topeka, KS",
  buttonLabel: "Start your journey",
  imgStart: "start",
  img: "/images/magdy.jpg",
  alt: "Man with black shirt and glasses sitting at a table",
  start: "true",
  route: "/signup",
};

export const review8 = {
  primary: true,
  lightBg: false,
  lightTopLine: false,
  lightTopLine2: false,
  lightText: true,
  lightTextDesc: true,
  topLine: "Kristen Ford",
  headline: "Never, ever give up.",
  description:
    "I sustained brain damage from an accident several years ago that left me partially paralyzed, and in a lot of pain. I had to learn how to eat, walk, and talk all over again, and I thought my life was over. The awesome staff at Code Command believed in me even when I didn’t believe in myself. Thanks to them I am now working for a great company designing user interfaces for people with disabilities.",
  role: "UI/UX Designer, Cobalt Systems, Inc",
  location: "Orlando, FL",
  buttonLabel: "Start your journey",
  imgStart: "",
  img: "/images/kristen.jpg",
  alt: "Young woman with red hair and tatoos sitting in a coffee shop grinning at her laptop",
  start: "",
  route: "/signup",
};

export const review9 = {
  primary: true,
  lightBg: true,
  lightTopLine: false,
  lightTopLine2: false,
  lightText: false,
  lightTextDesc: false,
  topLine: "Troy Mihalko",
  headline: "I’m lovin it…",
  description:
    "I have worked at McDonald’s since I was 15 years old, eventually making to store manager then regional manager, but then my career stalled out. Code Command’s full stack development course gave me the necessary skills to land a job at the corporate office designing websites and digital marketing campaigns.",
  role: "Product Manager, McDonald’s Corporation",
  location: "Oak Brook, IL",
  buttonLabel: "Start your journey",
  imgStart: "start",
  img: "/images/troy.jpg",
  alt: "Man with red shirt and clenched fists smiling triumphantly",
  start: "true",
  route: "/signup",
};

export const review10 = {
  primary: true,
  lightBg: false,
  lightTopLine: false,
  lightTopLine2: false,
  lightText: true,
  lightTextDesc: true,
  topLine: "Anthony Jenkins",
  headline: "Plan B is for wimps..",
  description:
    "I spent ten years in the transportation industry as a freight broker. The money was good, but I hated every second of it. I wanted to switch careers but couldn’t find anything that paid as well as my current job. When I finally had enough, I quit my job and enrolled in Code Command. I put everything on the line and almost ended up homeless, but now I have a job that I’m excited to go to every morning – and I stay paid.",
  role: "Project Manager, Davis Manufacturing, LLC",
  location: "Sheboygan, WI",
  buttonLabel: "Start your journey",
  imgStart: "",
  img: "/images/anthony.jpg",
  alt: "Suave looking man wearing a dark dray suit",
  start: "",
  route: "/signup",
};
